//! `CfsTrait` impl for [`crate::ShastaClient`].

use std::pin::Pin;

use chrono::NaiveDateTime;
use futures::AsyncBufRead;
#[cfg(feature = "k8s-console")]
use futures::AsyncReadExt;
#[cfg(feature = "k8s-console")]
use manta_backend_dispatcher::types::K8sAuth;
use manta_backend_dispatcher::{
  error::Error,
  interfaces::cfs::CfsTrait,
  types::{
    K8sDetails,
    bos::session_template::BosSessionTemplate,
    bss::BootParameters,
    cfs::{
      cfs_configuration_details::LayerDetails,
      cfs_configuration_request::CfsConfigurationRequest,
      cfs_configuration_response::{CfsConfigurationResponse, Layer},
      session::{CfsSessionGetResponse, CfsSessionPostRequest},
    },
    ims::Image as FrontEndImage,
  },
};

use crate::ShastaClient;
use crate::common::jwt_ops;
// `GroupExt::get_members` replaces the old inherent
// `Group::get_members` method (the type is now generated by
// progenitor and can't carry inherent impls in this crate).
use crate::hsm::group::GroupExt;
#[cfg(feature = "k8s-console")]
use crate::common::{
  kubernetes, vault::http_client::fetch_shasta_k8s_secrets_from_vault,
};

impl CfsTrait for ShastaClient {
  type T = Pin<Box<dyn AsyncBufRead + Send>>;

  async fn get_cfs_health(&self) -> Result<(), Error> {
    crate::cfs::health::test_connectivity_to_backend(self.base_url.as_str())
      .await
      .map_err(Error::from)
  }

  async fn post_session(
    &self,
    shasta_token: &str,
    session: &CfsSessionPostRequest,
  ) -> Result<CfsSessionGetResponse, Error> {
    self
      .cfs_session_v3_post(shasta_token, &session.clone().into())
      .await
      .map(std::convert::Into::into)
      .map_err(Error::from)
  }

  /// Fetch CFS sessions. Ref: <https://apidocs.svc.cscs.ch/paas/cfs/operation/get_sessions/>.
  async fn get_sessions(
    &self,
    shasta_token: &str,
    session_name_opt: Option<&String>,
    limit_opt: Option<u8>,
    after_id_opt: Option<String>,
    min_age_opt: Option<String>,
    max_age_opt: Option<String>,
    status_opt: Option<String>,
    name_contains_opt: Option<String>,
    is_succeded_opt: Option<bool>,
    tags_opt: Option<String>,
  ) -> Result<Vec<CfsSessionGetResponse>, Error> {
    // Get local/backend CFS sessions
    let local_cfs_session_vec = self
      .cfs_session_v3_get(
        shasta_token,
        session_name_opt,
        limit_opt,
        after_id_opt,
        min_age_opt,
        max_age_opt,
        status_opt,
        name_contains_opt,
        is_succeded_opt,
        tags_opt,
      )
      .await;

    // Convert to manta session

    local_cfs_session_vec
      .map(|cfs_session_vec| {
        cfs_session_vec
          .into_iter()
          .map(std::convert::Into::into)
          .collect::<Vec<CfsSessionGetResponse>>()
      })
      .map_err(Error::from)
  }

  async fn get_and_filter_sessions(
    &self,
    shasta_token: &str,
    hsm_group_name_vec: Vec<String>,
    xname_vec: Vec<&str>,
    min_age_opt: Option<&String>,
    max_age_opt: Option<&String>,
    type_opt: Option<&String>,
    status_opt: Option<&String>,
    cfs_session_name_opt: Option<&String>,
    limit_number_opt: Option<&u8>,
    is_succeded_opt: Option<bool>,
  ) -> Result<Vec<CfsSessionGetResponse>, Error> {
    if !hsm_group_name_vec.is_empty() && !xname_vec.is_empty() {
      return Err(Error::Message(
        "Cannot filter by both HSM group names and xnames simultaneously"
          .to_string(),
      ));
    }

    let mut hsm_group_available_vec =
      crate::hsm::group::utils::get_group_available(
        shasta_token,
        &self.base_url,
        &self.root_cert,
      )
      .await
      // .map_err(Error::from)?;
      .map_err(Error::from)?;

    let (hsm_group_name_vec, xname_vec) = if !hsm_group_name_vec.is_empty() {
      // Filter HSM groups based on argument. `Group.label` is now
      // `ResourceName(pub String)`; reach into `.0` for the comparison.
      hsm_group_available_vec
        .retain(|group| hsm_group_name_vec.contains(&group.label.0));

      if hsm_group_available_vec.is_empty() {
        return Err(Error::Message(
          "None of the requested HSM groups are available".to_string(),
        ));
      }

      let mut member_available_vec = hsm_group_available_vec
        .iter()
        .flat_map(GroupExt::get_members)
        .collect::<Vec<String>>();

      member_available_vec.sort();
      member_available_vec.dedup();

      (
        hsm_group_available_vec
          .into_iter()
          .map(|group| group.label.0)
          .collect::<Vec<String>>(),
        member_available_vec,
      )
    } else if !xname_vec.is_empty() {
      // Filter members available in the target HSM groups
      hsm_group_available_vec.retain(|group| {
        group
          .get_members()
          .iter()
          .any(|member| xname_vec.contains(&member.as_str()))
      });

      if hsm_group_available_vec.is_empty() {
        return Err(Error::Message(
          "None of the requested xnames are available in the target HSM groups"
            .to_string(),
        ));
      }

      (
        hsm_group_available_vec
          .into_iter()
          .map(|group| group.label.0)
          .collect(),
        xname_vec
          .into_iter()
          .map(std::string::ToString::to_string)
          .collect(),
      )
    } else {
      // all HSM groups available
      // all members available
      let member_available_vec = hsm_group_available_vec
        .iter()
        .flat_map(GroupExt::get_members)
        .collect::<Vec<String>>();

      (
        hsm_group_available_vec
          .into_iter()
          .map(|group| group.label.0)
          .collect(),
        member_available_vec,
      )
    };

    let mut cfs_session_vec = crate::cfs::session::get_and_sort(
      shasta_token,
      &self.base_url,
      &self.root_cert,
      min_age_opt,
      max_age_opt,
      status_opt,
      cfs_session_name_opt,
      is_succeded_opt,
    )
    .await
    // .map_err(Error::from)?;
    .map_err(Error::from)?;

    crate::cfs::session::utils::filter(
      &mut cfs_session_vec,
      None,
      &hsm_group_name_vec,
      &xname_vec,
      type_opt,
      limit_number_opt,
      jwt_ops::is_user_admin(shasta_token),
    )
    // .map_err(Error::from)?;
    .map_err(Error::from)?;

    if cfs_session_vec.is_empty() {
      return Err(Error::SessionNotFound);
    }

    for cfs_session in &mut cfs_session_vec {
      log::debug!("CFS session:\n{cfs_session:#?}");

      if cfs_session.is_target_def_image() && cfs_session.is_success() {
        log::info!(
          "Find image ID related to CFS configuration {} in CFS session {}",
          cfs_session.configuration_name().ok_or_else(|| {
            Error::Message(
              "ERROR - could not get configuration name from CFS session"
                .to_string(),
            )
          })?,
          cfs_session.name
        );

        let new_image_id_opt = if cfs_session
          .status
          .as_ref()
          .and_then(|status| {
            status.artifacts.as_ref().and_then(|artifacts| {
              artifacts
                .first()
                .and_then(|artifact| artifact.result_id.clone())
            })
          })
          .is_some()
        {
          let image_id = cfs_session.first_result_id();

          let new_image_vec_rslt: Result<
            Vec<crate::ims::image::http_client::types::Image>,
            _,
          > = self.ims_image_get(shasta_token, image_id).await;

          if let Ok(Some(new_image)) = new_image_vec_rslt
            .as_ref()
            .map(|new_image_vec| new_image_vec.first())
          {
            Some(new_image.clone().id.unwrap_or_default())
          } else {
            None
          }
        } else {
          None
        };

        // TODO: this block was intended to overwrite the first artifact's
        // result_id with the resolved image id, but the chain ends in
        // `.clone()` so the mutation is applied to a discarded temporary
        // and has no effect. Replacing with an explicit no-op for now;
        // the actual mutation would need to navigate via `as_mut()` /
        // `get_mut(0)` on the live cfs_session.status.artifacts.
        let _ = new_image_id_opt;
      }
    }

    Ok(
      cfs_session_vec
        .into_iter()
        .map(std::convert::Into::into)
        .collect(),
    )
  }

  async fn delete_and_cancel_session(
    &self,
    shasta_token: &str,
    group_available_vec: &[manta_backend_dispatcher::types::Group],
    cfs_session: &manta_backend_dispatcher::types::cfs::session::CfsSessionGetResponse,
    cfs_component_vec: &[manta_backend_dispatcher::types::cfs::component::Component],
    bss_bootparameters_vec: &[BootParameters],
    dry_run: bool,
  ) -> Result<(), Error> {
    let group_available_vec: Vec<crate::hsm::group::types::Group> =
      group_available_vec
        .iter()
        .map(|group| group.clone().into())
        .collect();

    let cfs_session: crate::cfs::session::http_client::v2::types::CfsSessionGetResponse =
        cfs_session.clone().into();

    let cfs_component_vec: Vec<
      crate::cfs::component::http_client::v2::types::Component,
    > = cfs_component_vec
      .iter()
      .map(|component| component.clone().into())
      .collect();

    let bss_bootparameters_vec: Vec<crate::bss::types::BootParameters> =
      bss_bootparameters_vec
        .iter()
        .map(|bp| bp.clone().into())
        .collect();

    crate::cfs::cleanup_session::exec(
      self,
      shasta_token,
      group_available_vec,
      &cfs_session,
      &cfs_component_vec,
      &bss_bootparameters_vec,
      dry_run,
    )
    .await
    .map_err(Error::from)
  }

  async fn create_configuration_from_repos(
    &self,
    gitea_token: &str,
    gitea_base_url: &str,
    repo_name_vec: &[&str],
    local_git_commit_vec: &[&str],
    playbook_file_name_opt: Option<&str>,
  ) -> Result<CfsConfigurationRequest, Error> {
    Ok(crate::cfs::configuration::http_client::v3::types::cfs_configuration_request::CfsConfigurationRequest::create_from_repos(
            gitea_token,
            gitea_base_url,
            &self.root_cert,
            repo_name_vec,
            local_git_commit_vec,
            playbook_file_name_opt,
        ).await.map_err(Error::from)?.into())
  }

  async fn get_configuration(
    &self,
    auth_token: &str,
    configuration_name_opt: Option<&String>,
  ) -> Result<Vec<CfsConfigurationResponse>, Error> {
    let cfs_configuration_vec = self
      .cfs_configuration_v3_get(
        auth_token,
        configuration_name_opt.map(std::string::String::as_str),
      )
      .await
      .map_err(Error::from);

    cfs_configuration_vec.map(|config_vec| {
      config_vec
        .into_iter()
        .map(std::convert::Into::into)
        .collect()
    })
  }

  async fn get_and_filter_configuration(
    &self,
    shasta_token: &str,
    configuration_name: Option<&str>,
    configuration_name_pattern: Option<&str>,
    hsm_group_name_vec: &[String],
    since_opt: Option<NaiveDateTime>,
    until_opt: Option<NaiveDateTime>,
    limit_number_opt: Option<&u8>,
  ) -> Result<Vec<CfsConfigurationResponse>, Error> {
    crate::cfs::configuration::utils::get_and_filter(
      shasta_token,
      &self.base_url,
      &self.root_cert,
      configuration_name,
      configuration_name_pattern,
      hsm_group_name_vec,
      since_opt,
      until_opt,
      limit_number_opt,
    )
    .await
    .map(|config_vec| {
      config_vec
        .into_iter()
        .map(std::convert::Into::into)
        .collect()
    })
    .map_err(Error::from)
  }

  async fn get_configuration_layer_details(
    &self,
    gitea_base_url: &str,
    gitea_token: &str,
    layer: Layer,
    site_name: &str,
  ) -> Result<LayerDetails, Error> {
    crate::cfs::configuration::utils::get_configuration_layer_details(
      &self.root_cert,
      gitea_base_url,
      gitea_token,
      layer.into(),
      site_name,
    )
    .await
    .map(std::convert::Into::into)
    .map_err(std::convert::Into::into)
  }

  /// Create a new CFS configuration
  async fn put_configuration(
    &self,
    shasta_token: &str,
    configuration: &CfsConfigurationRequest,
    configuration_name: &str,
    overwrite: bool,
  ) -> Result<CfsConfigurationResponse, Error> {
    crate::cfs::configuration::utils::create_new_configuration(
      shasta_token,
      &self.base_url,
      &self.root_cert,
      &configuration.clone().into(),
      configuration_name,
      overwrite,
    )
    .await
    .map(std::convert::Into::into)
    .map_err(Error::from)
  }

  #[cfg(not(feature = "k8s-console"))]
  async fn get_session_logs_stream(
    &self,
    _shasta_token: &str,
    _site_name: &str,
    _cfs_session_name: &str,
    _timestamps: bool,
    _k8s: &K8sDetails,
  ) -> Result<Pin<Box<dyn AsyncBufRead + Send>>, Error> {
    Err(Error::Message(
      "get_session_logs_stream requires the 'k8s-console' Cargo feature"
        .to_string(),
    ))
  }

  /// Stream the concatenated stdout of a CFS session's `git-clone`
  /// init container, then its `inventory` container, then its
  /// `ansible` container.
  ///
  /// # Cancellation
  ///
  /// The returned `Pin<Box<dyn AsyncBufRead + Send>>` is a `Chain`
  /// of three hyper response-body adapters from `kube_client`. Each
  /// segment is a thin wrapper around the response body — there's no
  /// spawned watcher task to leak. Dropping the returned future mid-
  /// stream drops the current segment's hyper `Response`, which
  /// closes the connection to the Kubernetes API server. The API
  /// server stops streaming. The downstream segments are never
  /// attached because they're lazily constructed inside the chain.
  #[cfg(feature = "k8s-console")]
  async fn get_session_logs_stream(
    &self,
    shasta_token: &str,
    site_name: &str,
    cfs_session_name: &str,
    timestamps: bool,
    k8s: &K8sDetails,
  ) -> Result<Pin<Box<dyn AsyncBufRead + Send>>, Error> {
    let shasta_k8s_secrets = match &k8s.authentication {
      K8sAuth::Native {
        certificate_authority_data,
        client_certificate_data,
        client_key_data,
      } => {
        serde_json::json!({ "certificate-authority-data": certificate_authority_data, "client-certificate-data": client_certificate_data, "client-key-data": client_key_data })
      }
      K8sAuth::Vault { base_url } => fetch_shasta_k8s_secrets_from_vault(
        base_url,
        shasta_token,
        site_name,
      )
      .await
      .map_err(Error::from)?,
    };

    let client = kubernetes::get_client(
      &k8s.api_url,
      shasta_k8s_secrets,
    )
    .await
    .map_err(Error::from)?;

    let (log_stream_git_clone, exit_code) =
      kubernetes::get_cfs_session_init_container_git_clone_logs_stream(
        client.clone(),
        cfs_session_name.to_string(),
        timestamps,
      )
      .await
      .map_err(Error::from)?;

    if exit_code != 0 {
      log::error!(
        "CFS session '{cfs_session_name}' git-clone init container failed with exit code {exit_code}"
      );
      return Ok(Box::pin(log_stream_git_clone));
    }

    let log_stream_inventory =
      kubernetes::get_cfs_session_container_inventory_logs_stream(
        client.clone(),
        cfs_session_name.to_string(),
        timestamps,
      )
      .await
      .map_err(Error::from)?;

    let log_stream_ansible =
      kubernetes::get_cfs_session_container_ansible_logs_stream(
        client,
        cfs_session_name.to_string(),
        timestamps,
      )
      .await
      .map_err(Error::from)?;

    // NOTE: here is where we convert from impl AsyncBufRead to Pin<Box<dyn AsyncBufRead>>
    // through dynamic dispatch
    Ok(Box::pin(
      log_stream_git_clone
        .chain(log_stream_inventory)
        .chain(log_stream_ansible),
    ))
  }

  async fn update_runtime_configuration(
    &self,
    shasta_token: &str,
    xnames: &[String],
    desired_configuration: &str,
    enabled: bool,
  ) -> Result<(), Error> {
    crate::cfs::component::utils::update_component_list_desired_configuration(
      shasta_token,
      &self.base_url,
      &self.root_cert,
      xnames,
      desired_configuration,
      enabled,
    )
    .await
    .map_err(Error::from)
  }

  // Get all CFS sessions, IMS images and BOS sessiontemplates related to a CFS configuration
  async fn get_derivatives(
    &self,
    shasta_token: &str,
    configuration_name: &str,
  ) -> Result<
    (
      Option<Vec<CfsSessionGetResponse>>,
      Option<Vec<BosSessionTemplate>>,
      Option<Vec<FrontEndImage>>,
    ),
    Error,
  > {
    crate::cfs::configuration::utils::get_derivatives(
      shasta_token,
      &self.base_url,
      &self.root_cert,
      configuration_name,
    )
    .await
    .map(|(cfs_session_vec, bos_session_template_vec, image_vec)| {
      (
        cfs_session_vec.map(|cfs_session_vec| {
          cfs_session_vec
            .into_iter()
            .map(std::convert::Into::into)
            .collect()
        }),
        bos_session_template_vec.map(|bos_session_template_vec| {
          bos_session_template_vec
            .into_iter()
            .map(std::convert::Into::into)
            .collect()
        }),
        image_vec.map(|image_vec| {
          image_vec
            .into_iter()
            .map(std::convert::Into::into)
            .collect()
        }),
      )
    })
    .map_err(Error::from)
  }

  async fn get_cfs_components(
    &self,
    shasta_token: &str,
    configuration_name: Option<&str>,
    components_ids: Option<&str>,
    status: Option<&str>,
  ) -> Result<
    Vec<manta_backend_dispatcher::types::cfs::component::Component>,
    Error,
  > {
    // When the caller doesn't specify any ids, do NOT route through
    // `cfs_component_v3_get_query_batch` — `parallel_batch` short-circuits
    // on an empty input slice and never issues a request, silently
    // dropping any `configuration_name`/`status` filters. Send a single
    // GET (no `ids` query param) instead, which is what every consumer
    // of "all components matching this filter" expects.
    let component_vec = if let Some(component_ids) = components_ids {
      let xname_vec: Vec<String> =
        component_ids.split(',').map(|v| v.to_string()).collect();
      self
        .cfs_component_v3_get_query_batch(
          shasta_token,
          configuration_name.map(|v| v.to_string()),
          &xname_vec,
          status.map(|v| v.to_string()),
        )
        .await
    } else {
      self
        .cfs_component_v3_get_query(
          shasta_token,
          configuration_name,
          None,
          status,
        )
        .await
    };

    component_vec
      .map(|cs| cs.into_iter().map(std::convert::Into::into).collect())
      .map_err(Error::from)
  }
}
