//! `ConsoleTrait` impl for [`crate::ShastaClient`].

use futures_channel::mpsc::Sender;
use kube::api::{AttachedProcess, TerminalSize};
use manta_backend_dispatcher::{
  error::Error,
  interfaces::console::{ConsoleAttachment, ConsoleTrait, TermSize},
  types::{K8sAuth, K8sDetails},
};

use crate::ShastaClient;
use crate::{
  common::vault::http_client::fetch_shasta_k8s_secrets_from_vault,
  node::console,
};

/// Channel depth for the manta -> kube terminal-resize forwarder.
///
/// 8 is a safe upper bound on the number of unprocessed resize events
/// we might buffer: each event is 4 bytes (two u16s), the forwarder
/// drains synchronously, and resize events are inherently low-rate
/// (only generated by user terminal resizes). If the channel fills, the
/// caller's `try_send` would drop the event, which is the right
/// behavior — terminal sizes are idempotent state, not a sequence
/// of deltas, so dropping intermediate resizes only causes a one-frame
/// stale view that the next event corrects.
const RESIZE_CHANNEL_CAPACITY: usize = 8;

/// Spawn a forwarder task that bridges manta's resize channel to kube's.
///
/// Returns a [`tokio::sync::mpsc::Sender<TermSize>`] that the caller
/// stores in [`ConsoleAttachment::resize`]. Each value the caller sends
/// is forwarded into `kube_resize`. The forwarder exits when the caller
/// drops the returned sender; when it exits, `kube_resize` is dropped,
/// which signals kube's exec subprotocol to tear down channel 4.
///
/// Errors when forwarding to kube (closed receiver, channel full) are
/// swallowed: the console session itself remains usable through stdin/
/// stdout, and a dropped resize event just means the next one resyncs
/// the dimensions.
fn spawn_resize_forwarder(
  mut kube_resize: Sender<TerminalSize>,
) -> tokio::sync::mpsc::Sender<TermSize> {
  let (manta_tx, mut manta_rx) =
    tokio::sync::mpsc::channel::<TermSize>(RESIZE_CHANNEL_CAPACITY);
  tokio::spawn(async move {
    while let Some(size) = manta_rx.recv().await {
      let _ = kube_resize.try_send(TerminalSize {
        width: size.width,
        height: size.height,
      });
    }
  });
  manta_tx
}

impl ConsoleTrait for ShastaClient {
  async fn attach_to_node_console(
    &self,
    shasta_token: &str,
    site_name: &str,
    xname: &str,
    initial_size: TermSize,
    k8s: &K8sDetails,
  ) -> Result<ConsoleAttachment, Error> {
    let shasta_k8s_secrets = match &k8s.authentication {
      K8sAuth::Native {
        certificate_authority_data,
        client_certificate_data,
        client_key_data,
      } => {
        serde_json::json!({ "certificate-authority-data": certificate_authority_data, "client-certificate-data": client_certificate_data, "client-key-data": client_key_data })
      }
      K8sAuth::Vault {
        base_url,
        // secret_path: _secret_path,
      } => fetch_shasta_k8s_secrets_from_vault(
        base_url,
        shasta_token,
        site_name,
      )
      .await
      .map_err(Error::from)?,
    };

    let mut attached: AttachedProcess =
      console::get_container_attachment_to_conman(
        xname,
        &k8s.api_url,
        shasta_k8s_secrets,
      )
      .await
      .map_err(Error::from)?;

    let pod = xname;
    let mut terminal_size_writer: Sender<TerminalSize> =
      attached.terminal_size().ok_or_else(|| {
        crate::Error::ConsoleAttach {
          pod: pod.to_string(),
          cause: "kube exec did not provide a terminal-size channel".to_string(),
        }
      })?;
    terminal_size_writer
      .try_send(TerminalSize {
        width: initial_size.width,
        height: initial_size.height,
      })
      .map_err(|e| crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: e.to_string(),
      })?;

    // Bridge manta's resize channel to kube's. The forwarder task exits
    // when the manta-side sender is dropped (caller closes the console),
    // which then drops `terminal_size_writer` and ends kube's resize
    // subprotocol cleanly.
    let resize_tx = spawn_resize_forwarder(terminal_size_writer);

    log::info!("Connected to {xname}!");
    log::info!("Use &. key combination to exit the console.");

    let stdin = attached.stdin().ok_or_else(|| {
      crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: "kube exec did not provide a stdin stream".to_string(),
      }
    })?;
    let stdout = attached.stdout().ok_or_else(|| {
      crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: "kube exec did not provide a stdout stream".to_string(),
      }
    })?;
    Ok(ConsoleAttachment {
      stdin: Box::new(stdin),
      stdout: Box::new(stdout),
      resize: resize_tx,
    })
  }

  async fn attach_to_session_console(
    &self,
    shasta_token: &str,
    site_name: &str,
    session_name: &str,
    initial_size: TermSize,
    k8s: &K8sDetails,
  ) -> Result<ConsoleAttachment, Error> {
    let shasta_k8s_secrets = match &k8s.authentication {
      K8sAuth::Native {
        certificate_authority_data,
        client_certificate_data,
        client_key_data,
      } => {
        serde_json::json!({ "certificate-authority-data": certificate_authority_data, "client-certificate-data": client_certificate_data, "client-key-data": client_key_data })
      }
      K8sAuth::Vault {
        base_url,
        // secret_path: _secret_path,
      } => fetch_shasta_k8s_secrets_from_vault(
        base_url,
        shasta_token,
        site_name,
      )
      .await
      .map_err(Error::from)?,
    };

    let mut attached: AttachedProcess =
      console::get_container_attachment_to_cfs_session_image_target(
        session_name,
        &k8s.api_url,
        shasta_k8s_secrets,
      )
      .await
      .map_err(Error::from)?;

    let pod = session_name;
    let mut terminal_size_writer: Sender<TerminalSize> =
      attached.terminal_size().ok_or_else(|| {
        crate::Error::ConsoleAttach {
          pod: pod.to_string(),
          cause: "kube exec did not provide a terminal-size channel".to_string(),
        }
      })?;
    terminal_size_writer
      .try_send(TerminalSize {
        width: initial_size.width,
        height: initial_size.height,
      })
      .map_err(|e| crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: e.to_string(),
      })?;

    // Bridge manta's resize channel to kube's. The forwarder task exits
    // when the manta-side sender is dropped (caller closes the console),
    // which then drops `terminal_size_writer` and ends kube's resize
    // subprotocol cleanly.
    let resize_tx = spawn_resize_forwarder(terminal_size_writer);

    log::info!(
      "Connected to session target container for session name: {session_name}!"
    );
    log::info!("Use &. key combination to exit the console.");

    let stdin = attached.stdin().ok_or_else(|| {
      crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: "kube exec did not provide a stdin stream".to_string(),
      }
    })?;
    let stdout = attached.stdout().ok_or_else(|| {
      crate::Error::ConsoleAttach {
        pod: pod.to_string(),
        cause: "kube exec did not provide a stdout stream".to_string(),
      }
    })?;
    Ok(ConsoleAttachment {
      stdin: Box::new(stdin),
      stdout: Box::new(stdout),
      resize: resize_tx,
    })
  }
}
